# Generated by Django 3.0.6 on 2020-05-16 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリー', 'verbose_name_plural': 'カテゴリー'},
        ),
        migrations.AlterModelOptions(
            name='kakeibo',
            options={'verbose_name': '家計簿', 'verbose_name_plural': '家計簿'},
        ),
        migrations.AlterField(
            model_name='kakeibo',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 0, 38, 12, 442305), verbose_name='日付'),
        ),
    ]
